BOARD := nodemcuv2
UPLOAD_SPEED := 115200

CUSTOM_LIBS := ../libraries

ARDUINO_LIBS += Adafruit_Sensor
ARDUINO_LIBS += DHT-sensor-library

BUILD_ROOT := build
ESP_ROOT := ../esp-toolchain
include ../makeEspArduino/makeEspArduino.mk
